---
name: ci
on: [push, pull_request]
jobs:
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: Build
        run: go build -race  ./...
      - name: Test
        run: go test -race  `go list ./... | grep -v e2e`
  go-lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golint
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: './...'
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          args: --timeout=10m --tests="false"
          version: v1.47.0
  style-check:
    name: gofmt and goimports
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Install dependencies
        run: |
          go version
          go install golang.org/x/tools/cmd/goimports@latest
      - name: gofmt and goimports
        run: make style-check
  checkgomod:
    name: check go.mod and go.sum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - run: go mod tidy
      - name: Check for changes in go.mod or go.sum
        run: |
          git diff --name-only --exit-code go.mod || ( echo "Run go tidy" && false )
          git diff --name-only --exit-code go.sum || ( echo "Run go tidy" && false )
