name: Auto Build and Push image

on:
  create

jobs:
  publish_image:
    name: Build and Push consul2istio image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Extract Tags name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: tag_env
        shell: bash
        run: |
          echo "##[set-output name=version;]$(echo ${GITHUB_REF##*/})"

      - name: Extract Tags Type
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: tag_type
        shell: bash
        run: |
          echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build consul2istio Docker Image
        if: ${{ startsWith(steps.tag_type.outputs.version, 'consul2istio/') }}
        run: |
          make docker-build tag=${{ steps.tag_env.outputs.version }}

      - name: Push Aeraki Docker image
        if: ${{ startsWith(steps.tag_type.outputs.version, 'aeraki/') }}
        run: |
          docker push ghcr.io/aeraki-mesh/consul2istio:${{ steps.tag_env.outputs.version }}
